name: Meal Notifier

on:
  schedule:
    - cron: "30 23 * * 0-5"  # 5 AM IST (23:30 UTC, Mon-Sat)
    - cron: "30 11 * * 0-5"  # 5 PM IST (11:30 UTC, Mon-Sat)
  workflow_dispatch:         # allow manual trigger too

jobs:
  send-meal-menu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build
        run: go build -o meal-notifier main.go

      - name: Run script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
          TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
          TWILIO_WHATSAPP_TO: ${{ secrets.TWILIO_WHATSAPP_TO }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: ./meal-notifier
